name: Render full stl
on:
  push: 
    branches:
      - master
jobs:
  full:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2
      - name: Render full image
        uses: vlegio/openscad-actions@v2.0
        with:
          scad_file: assembled.scad
          output_file: assembled.stl
          options: "-D q=100"

